### ISSUE TITLE
Downside of Round-Robin load balancing, and cache-awareness

### ISSUE THREAD

**Issue by metalalive** [leandromoreira/cdn-up-and-running#10]
Hi, could you please explain how cache-awareness leads to the downside of Round-Robin load balancing ?

According to [`round-robin` part](https://github.com/leandromoreira/cdn-up-and-running#round-robin) of the article :
> What's not good about it? It's not caching-aware, meaning multiple clients will face higher latencies because they're asking uncached servers.

Here is my understanding,  when multiple clients ask for uncached content,  the latency of the concurrent client requests comes from [coalescing](https://cloud.google.com/cdn/docs/caching#request-coalescing) (the Nginx directive `proxy_cache_lock`) , only one request passed to upstream server, all other client requests simply wait until the fresh content is cached.  It is probably not related to Round-Robin load balancing ?

thanks for the reply.

**Comment by leandromoreira** [comment]
Hi @metalalive =) sure, I'll try to provide my reasoning behind that sentence:

> Here is my understanding, when multiple clients ask for uncached content, the latency of the concurrent client requests comes from [coalescing](https://cloud.google.com/cdn/docs/caching#request-coalescing) (the Nginx directive proxy_cache_lock) , only one request passed to upstream server, all other client requests simply wait until the fresh content is cached. It

Your understanding seems right to me :)! The main idea is to serve fast, save bandwidth, save storage, avoid extra hops, etc.

Think about a CDN, with `100 nodes`, where you have an unpopular content `video.mp4` being accessed by `100 users`. Since you're using `RR`, as the load balancing police, **every SINGLE user will pay the latency** because each server does not have the content cached in its area (that's the cache unawareness). You can add on top of that the disks/SSD storage will be filled with content that could be better distributed.

However, if you have hugely popular content with millions of users the `RR` might be good enough at a CDN level, assuming that the user was directed to the closest CDN (like in their ISP, or city). There's even a better algorithm than `RR` alone with, I'd say, almost the same characteristics, the [random of two](https://brooker.co.za/blog/2012/01/17/two-random.html)

The graph bellow shows that `Alice, Bob, and Carol` all paid the extra latency cost, and the CDN itself paid the cost of leaving the DC to fetch the source object (assuming a pull only nature). One can argue that you could organize your nodes, within the CDN, to avoid some of these issues.

I think it all boils down to behaving differently for different situations, trying to serve fast content for popular and unpopular content requires different strategies. Does that make sense?

```mermaid
flowchart LR
    A[Alice] -->|Get /video.mp4| RR{RR}
    RR -->|Sends Alices to| S1{Server1}
    B[Bob] -->|Get /video.mp4| RR
    RR -->|Sends Bob to| S2{Server2}
    C[Carol] -->|Get /video.mp4| RR
    RR -->|Sends Carol to| S3{Server3}
    S1 -->|Fetches from origin| O{Origin}
    S2 -->|Fetches from origin| O{Origin}
    S3 -->|Fetches from origin| O{Origin}
```

**Comment by metalalive** [comment]
Can I view the `server 1` , `server 2` (in the diagrams above) as different nodes (like nginx servers) in a CDN ?
so the CDN with several nodes will face the caching issue you mentioned, when : 

- multiple frontend clients send requests  (for the same unpopular content)  to the same node (say `node1`) running round-robin load balancing (`RR`)
- since the `RR` is not aware of cache, `node1` passes the requests to all other  different nodes (e.g. `node 2`, `node 3`... etc) in a single CDN
- then all other different nodes connect to origin server (or upstream backend server), cache the unpopular content , have several copies in these nodes, that cause unnecessary waste of memory space in all the nodes of a CDN.

**Comment by leandromoreira** [comment]
All the drawing/graphics used were just to demonstrate an abstract concept. In reality a user request might follow:

1. A user requests content XYZ to API/DNS routing/Anycast
    * this part might work as the PoP load balancing 
      * **picking up the closest PoP (set of nodes)**, 
    * and also the node balancing within the PoP 
      * **picking up the best node, caching/resource aware**
2. API/DNS routing/Anycast returns/resolve to the closest NODE
3. The user watches the stream/downloads the game/assets, etc
4. If the content is in the cache it just serves, if not it goes to the layered network of nodes (you can also think of it as a "tree")

![image](https://user-images.githubusercontent.com/55913/226510281-60f513a5-ac34-439a-a9d6-900ec721e50c.png)

**Comment by metalalive** [comment]
Yes, in reality the PoP load balancing will do thing more intelligently , thanks for explaining
